services:
  bigbro-nginx:
    container_name: bigbro-nginx
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - bigbro-application

  bigbro-application:
    container_name: bigbro-application
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ~/.env
    ports:
      - "8000:8000"
