services:
  bigbro-nginx:
    container_name: bigbro-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/
    networks:
      - bigbro-network
    depends_on:
      - bigbro-application

  bigbro-application:
    container_name: bigbro-application
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ~/.env
    networks:
      - bigbro-network
    depends_on:
      - bigbro-postgres
      - bigbro-redis

  bigbro-postgres:
    container_name: bigbro-postgres
    image: postgres:16
    restart: always
    volumes:
      - bigbro-postgres:/var/lib/postgresql/data
    env_file:
      - ~/.env
    networks:
      - bigbro-network

  bigbro-redis:
    container_name: bigbro-redis
    image: redis:6
    restart: always
    networks:
      - bigbro-network

networks:
  bigbro-network:
    driver: bridge

volumes:
  bigbro-postgres:
    driver: local
