# Generated by Django 5.2.3 on 2025-06-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paymentkey",
            field=models.CharField(null=True),
        ),
    ]
