# Generated by Django 5.1.5 on 2025-02-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
