# Generated by Django 5.2.3 on 2025-06-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_remove_orderitem_status_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(default="NULL", max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="receipt_url",
            field=models.CharField(null=True),
        ),
    ]
