# Generated by Django 5.1.5 on 2025-02-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_orderitem_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="traking_number",
            new_name="tracking_number",
        ),
    ]
