# Generated by Django 5.2.3 on 2025-06-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_name_order_receipt_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paymentkey",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="receipt_url",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
