# Generated by Django 5.1.7 on 2025-06-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PURCHASED', 'Purchased'), ('PREPARING', 'Prepare Ship'), ('SHIPPING_STARTED', 'Start Ship'), ('IN_SHIPPING', 'In Ship'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed')], max_length=16),
        ),
    ]
