# Generated by Django 5.1.7 on 2025-06-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('STAGING', 'Staging'), ('PURCHASED', 'Purchased'), ('PREPARING', 'Prepare Ship'), ('SHIPPING_STARTED', 'Start Ship'), ('IN_SHIPPING', 'In Ship'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed')], default='STAGING', max_length=16),
        ),
    ]
