# Generated by Django 5.1.7 on 2025-06-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderitem_price_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('STAGING', 'Staging'), ('PURCHASED', 'Purchased'), ('PREPARING', 'Prepare Ship'), ('START_SHIP', 'Start Ship'), ('IN_SHIP', 'In Ship'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed')], default='STAGING', max_length=16),
        ),
    ]
