# Generated by Django 5.2.3 on 2025-06-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_delivery_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_price',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.PositiveIntegerField(default=3000),
        ),
    ]
