# Generated by Django 5.1.5 on 2025-01-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("BIGBRO", "Bigbro"),
                            ("S.C.B", "Scb"),
                            ("SCULFEE", "Sculfee"),
                            ("GONGNEWGI", "Gongnewgi"),
                            ("CBWAS", "Cbwas"),
                        ],
                        max_length=9,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("price", models.PositiveIntegerField()),
                ("discount", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ON", "On"), ("OFF", "Off"), ("EMPTY", "Empty")],
                        max_length=5,
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "product",
            },
        ),
    ]
