# Generated by Django 5.2.4 on 2025-07-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.URLField(max_length=500),
        ),
    ]
