# Generated by Django 5.1.5 on 2025-01-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productimage_productoption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.URLField(),
        ),
    ]
