services:
  nginx:
    container_name: nginx
    image: nginx:1.27
    ports:
      - "80:80"
    volumes:
      - ../nginx:/etc/nginx/conf.d

  web-blue:
    container_name: web-blue
    build:
      dockerfile: Dockerfile
      context: ../../
    env_file:
      - ../../.env

  web-green:
    container_name: web-green
    build:
      dockerfile: Dockerfile
      context: ../../
    env_file:
      - ../../.env
