services:
  stage-web:
    container_name: stage-web
    build:
      dockerfile: Dockerfile
      context: ../../
    env_file:
      - ../../.env.stage
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.stage
    command: [
      "/bin/sh", "-c",
      "poetry run python src/manage.py migrate &&
      poetry run gunicorn --chdir ./src/ --bind 0.0.0.0:8001 --workers 3 core.wsgi:application"
    ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - stage-postgres
      - stage-redis

  stage-postgres:
    container_name: stage-postgres
    image: postgres:16
    restart: always
    volumes:
      - stage-postgres:/data/bigbro/stage/postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  stage-redis:
    container_name: stage-redis
    image: redis:6
    restart: always
    volumes:
      - stage-redis:/data/bigbro/stage/redis

volumes:
  stage-postgres:
  stage-redis: