services:
  nginx:
    container_name: nginx
    image: nginx:1.27
    ports:
      - "80:80"
    volumes:
      - ../nginx:/etc/nginx/conf.d

  web-blue:
    container_name: web-blue
    build:
      dockerfile: Dockerfile
      context: ../../
    env_file:
      - ../../.env
    depends_on:
      - postgres
      - redis
      - nginx

  web-green:
    container_name: web-green
    build:
      dockerfile: Dockerfile
      context: ../../
    env_file:
      - ../../.env
    depends_on:
      - postgres
      - redis
      - nginx

  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    volumes:
      - postgres:/data/bigbro/postgres
    env_file:
      - ../../.env

  redis:
    container_name: redis
    image: redis:6
    restart: always
    volumes:
      - redis:/data/bigbro/redis

volumes:
  postgres:
  redis: