services:
  nginx:
    container_name: nginx
    image: nginx:1.27
    ports:
      - "80:80"
    volumes:
      - ../nginx:/etc/nginx/conf.d
    depends_on:
      - stage-web
      - prod-web

  prod-web:
    container_name: prod-web
    build:
      dockerfile: Dockerfile
      context: ../../
    env_file:
      - ../../.env.prod
    depends_on:
      - prod-postgres
      - prod-redis

  stage-web:
    container_name: stage-web
    build:
      dockerfile: Dockerfile
      context: ../../
    env_file:
      - ../../.env.stage
    depends_on:
      - stage-postgres
      - stage-redis

  prod-postgres:
    container_name: prod-postgres
    image: postgres:16
    restart: always
    volumes:
      - prod-postgres:/data/bigbro/prod/postgres
    env_file:
      - ../../.env.prod

  prod-redis:
    container_name: prod-redis
    image: redis:6
    restart: always
    volumes:
      - prod-redis:/data/bigbro/prod/redis

  stage-postgres:
    container_name: stage-postgres
    image: postgres:16
    restart: always
    volumes:
      - stage-postgres:/data/bigbro/stage/postgres
    env_file:
      - ../../.env.stage

  stage-redis:
    container_name: stage-redis
    image: redis:6
    restart: always
    volumes:
      - stage-redis:/data/bigbro/stage/redis

volumes:
  prod-postgres:
  stage-postgres:
  prod-redis:
  stage-redis: