# Generated by Django 5.1.5 on 2025-01-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cart",
            table="cart",
        ),
    ]
