# Generated by Django 5.1.5 on 2025-01-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_alter_address_request"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="user_id",
            new_name="user",
        ),
    ]
