# Generated by Django 5.2.3 on 2025-06-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_address_default_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='request',
        ),
    ]
