name: Bigbro Stage CD Workflow

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_STAGE }}
          port: ${{ secrets.SSH_PORT_STAGE }}
          username: ${{ secrets.SSH_USERNAME_STAGE }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGE }}
          script: |
            set -e
            cd bigbro_company_server
            git pull origin develop
            ./deploy.sh