name: Bigbro Prod CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd bigbro_company_server
            git pull origin main
            docker-compose -f infra/compose/docker-compose.yml stop prod-web
            docker system prune -af --volumes=false
            docker-compose -f infra/compose/docker-compose.yml up -d --build prod-web
